### ISSUE TITLE
Possible modifications to script or running FIX alone? 

### ISSUE THREAD

**Issue by Abhijotsinghsidhu** [kytk/docker-fix#1]
Firstly, thank you so much for uploading this. FIX has been an absolute hassle to install, and I can’t seem to get it working on my local machine – your docker image was very helpful in overcoming this. 

Is it possible to modify the MELODIC script and/or just run FIX independently if I preprocess my functional data locally? For example, the default parameters of MELODIC don’t include slice-time correction and assume spatial smoothing should be conducted at 5mm. It would be great if the user could modify such parameters to cater to their data or just fun FIX independently of the MELODIC step. 

Thanks!
Abhi

**Comment by kytk** [comment]
@Abhijotsinghsidhu 

Thank you for asking.

## Modifications to script

I prepare individual-fix.sh to set some parameters such as slice timing correction or smoothing fwhm.

In Docker container, please do the following;

```
cd
cp /usr/local/bin/individual-fix.sh  my_individual-fix.sh
```

Now you see my_individual-fix.sh in your directory you bind to the docker.
(I did not install any text editors except for vi, so if you are not familiar with vi, please use your editor from your host machine.)

In the beginning of the script, you will see the following lines;

```
###Configuration#######################################

#Set FWHM
fwhm=5

#Set the number of volumes to be deleted (dummy volume)
delvol=4

#Slice timing correction
# 0 : None
# 1 : Regular up (0, 1, 2, 3, ...)
# 2 : Regular down
# 3 : Use slice order file
# 4 : Use slice timings file
# 5 : Interleaved (0, 2, 4 ... 1, 3, 5 ... )
st=1
######################################################
```

You can change the parameter as you wish.
For example, if you want to set FWHM=6, change fwhm=5 to fwhm=6

As of slice timing correction, you can choose the number to indicate what kind of slice timing correction should be made.

After editing the script, you can run

bash my_individual-fix.sh F_*.nii.gz

then everything should run with your settings.

## running FIX alone

This is very simple. Please run the following command. I suppose you bind the directory which contains *.ica (melodic output)

```
fix your_data.ica /usr/local/fix/training_files/Standard.RData 20 -m
```

Hope this helps,

Kiyotaka

**Comment by Abhijotsinghsidhu** [comment]
@kytk Thank you so much! This helps immensely.

Abhi
